### PR TITLE
Start making a glossary

### PR DESCRIPTION
**Pull request by reedy**
Makes a start on https://github.com/Map-A-Droid/MAD-docs/issues/50

### CODE REVIEW

**Comment by reedy** [comment]
Rebased

**Review by Expl0dingBanana — APPROVED** [review]

**Comment by reedy** [comment]
Anything needed to get this merged? :)

**Comment by reedy** [comment]
Helloooooooo?

**Comment by reedy** [comment]
Who do I need to .*? around here to get this one merged? ;)

**Comment by reedy** [comment]
Woo. Thanks!

**Pull request merged**
